version: '3.6'
services:

  postgres:
    build:
      context: db
      dockerfile: db.Dockerfile
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v2.0.10.cli-migrations-v3
    ports:
    - "3000:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
    - ./hasura/metadata:/hasura-metadata
    - ./hasura/migrations:/hasura-migrations
    - ./hasura/seeds:/hasura-seeds
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/realadvisor
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
#      HASURA_GRAPHQL_ADMIN_SECRET: realadvisorsecret

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: base
    environment:
      NODE_ENV: development
    volumes:
      - ./back/src:/home/node/app/src
      - ./back/nodemon.json:/home/node/app/nodemon.json
    expose:
      - '80'
    command: npm run dev

volumes:
  db_data:

